messenger4j:
  appSecret: EAACXZC1W4UnMBAH4MZAbjIoi5AZCIvJErMtrVkeZBVGT4DMOOU3KZA87a39BoNP1m3m0UJd6bqvAQZB2qIFZBxvsDGCkNqlUdwd3dSUdSlh1IlV3MZAldabhpOFc8bj1Xpj9eCiUy9NF6N9H3eCCpb49qEIDoZANNdVZAIuQzf8ZAdBDwZDZD
  verifyToken : ea994619-9fa3-402a-9ee3-3c9ffa5765c6
  pageAccessToken: EAACXZC1W4UnMBAH4MZAbjIoi5AZCIvJErMtrVkeZBVGT4DMOOU3KZA87a39BoNP1m3m0UJd6bqvAQZB2qIFZBxvsDGCkNqlUdwd3dSUdSlh1IlV3MZAldabhpOFc8bj1Xpj9eCiUy9NF6N9H3eCCpb49qEIDoZANNdVZAIuQzf8ZAdBDwZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
